---
#

- name: Install nginx with apt
  apt:
   name: nginx
   update_cache: yes
 
- name: start nginx
  service:
      name: nginx
      state: started

- name: copy the nginx config file and restart nginx
  copy:
    src: /c/Users/abdim/Documents/ELK/roles/nginx/static_site.cfg
    dest: /etc/nginx/sites-available/static_site.cfg
  become: yes
  - name: create symlink
    file:
      src: /etc/nginx/sites-available/static_site.cfg
      dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes
- name: copy the content of the web site
  copy:
    src: /c/Users/abdim/Documents/ELK/roles/nginx/static-site-src/
    dest: /home/static-site
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
