---


- name: check if file exists
  stat: 
    path: /etc/logstash/conf.d/nginx-01.conf
  register: files_to_delete

- name: removing file if exits
  file:
    path: /etc/logstash/conf.d/nginx-01.conf
    state: absent
  when: files_to_delete.stat.exists == True

- name: Create new file for processing apache2 access log files
  file:
    path: /etc/logstash/conf.d/nginx-01.conf
    state: touch
    owner: root
    group: root
    mode: '0644'


# Insert data into nginx access log file
- name: Insert data into access log file
  blockinfile:
    path: /etc/logstash/conf.d/nginx-01.conf
    block: |
      input {
        file {
          type => "nginx"
          path => "/var/log/nginx/*"
          exclude => "*.gz"
        }
      }
      filter {
        if [type] == "nginx" {
          grok {
        patterns_dir => "/etc/logstash/patterns"
        match => { "message" => "%{NGINX_ACCESS}" }
        remove_tag => ["grokparsefailure"]
        add_tag => ["nginx_access"]
          }
          geoip {
            source => "clientip"
          }
      output {
        elasticsearch {
          hosts => ["localhost:9200"]    
        }
      }
 
            
